### PR TITLE
Support for llm functions with complex objects and arrays

### PR DESCRIPTION
**Pull request by mayank-bairagi**
This pull request does the following

1. Update LLMFunction Schema to hold object properties and array items.
2. Enable AzureAIClient to create functions with nested schemas in OpenAI-supported format.

### CODE REVIEW

**Comment by patwlan** [comment]
Looking good. Question: is this schema specific to OpenAI or could we reuse it for Gemini?

**Comment by mayank-bairagi** [comment]
> Looking good. Question: is this schema specific to OpenAI or could we reuse it for Gemini?
This schema is specific to OpenAI and is closer to Gemini's schema than our LLMFunction schema, though slightly different from Gemini's.

Both OpenAI and Gemini use **JSON Schema** to define function inputs and outputs. Gemini allows functions to be defined using **OpenAPI**, which extends **JSON Schema** with additional features for REST APIs. OpenAI uses a subset of **JSON Schema**  to specify function parameters and validate structured outputs.

**Comment by patwlan** [comment]
ok. Looks good to merge. If you can just fix the checks.

**Comment by mayank-bairagi** [comment]
> ok. Looks good to merge. If you can just fix the checks.

There were Kotlin-style (ktlint) related issues, but those have been fixed now.

**Pull request merged**
